#!/bin/sh
#
# A script for tabbing through specifed project directories

# options:
#   repo, projects

tabbing_directory=""
case $1 in
"projects")
  tabbing_directory=${PROJECTS_DIR}
  ;;
"scratch")
  tabbing_directory=${REPOS_DIR}
  ;;
"repos")
  tabbing_directory=${SCRATCH_DIR}
  ;;
*)
  echo "Please pick a set dir from projects, sctrach or repos"
  exit 1
  ;;
esac

DIR_NAME="| xargs -r -I {} dirname {}"
ENTRY_OPTION="-type d -maxdepth 1"

# abilities
#   cd, code, editor
case $2 in
"cd")
  cd $(find ${tabbing_directory} ${ENTRY_OPTION} | fzf)
  ;;
"code")
  code $(find ${tabbing_directory} ${ENTRY_OPTION} | fzf)
  ;;
"editor")
  ${EDITOR} $(find ${tabbing_directory} ${ENTRY_OPTION} | fzf)
  ;;
*)
  echo "Please pick either cd or code or editor"
  exit 1
  ;;
esac
