# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
os:
  editPreset: "nvim"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never -s --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

customCommands:
  - key: "<c-c>"
    context: "files"
    prompts:
      - type: "input"
        title: "Add Commit Message - ticket prefix if found"
        key: "Message"

    description: "Prefix commit message"
    command: git commit -m "[$(git rev-parse --abbrev-ref HEAD | grep -Eo '^(\w+/)?(\w+[-_])?[0-9]+' | grep -Eo '(\w+[-])?[0-9]+')] {{.Form.Message}}"
